//
//  Config.swift
//  Selko
//
//  Created by Claude on 1/26/26.
//

import Foundation

enum Config {
    private enum InfoKey {
        static let supabaseURL = "SUPABASE_URL"
        static let supabaseAnonKey = "SUPABASE_ANON_KEY"
        static let apiURL = "SELKO_API_URL"
    }

    // Local Supabase demo anon key (same key used by web frontend and Android)
    // This is the standard key generated by `supabase start` for local development
    private static let localAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

    private static func value(for key: String, fallback: String? = nil) -> String {
        if let envValue = ProcessInfo.processInfo.environment[key], !envValue.isEmpty {
            return envValue
        }
        if let plistValue = Bundle.main.object(forInfoDictionaryKey: key) as? String,
           !plistValue.isEmpty {
            return plistValue
        }
        if let fallback {
            return fallback
        }
        return ""
    }

    static var supabaseURL: String {
        value(for: InfoKey.supabaseURL, fallback: "http://localhost:54321")
    }

    static var supabaseAnonKey: String {
        value(for: InfoKey.supabaseAnonKey, fallback: localAnonKey)
    }

    static var apiURL: String {
        value(for: InfoKey.apiURL, fallback: "http://localhost:8000")
    }
}
