//
//  Config.swift
//  Selko
//
//  Created by Claude on 1/26/26.
//

import Foundation

enum Config {
    // Local Supabase demo anon key (same key used by web frontend and Android)
    // This is the standard key generated by `supabase start` for local development
    private static let localAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

    static var supabaseURL: String {
        if let envURL = ProcessInfo.processInfo.environment["SUPABASE_URL"] {
            return envURL
        }
        #if DEBUG
        return "http://localhost:54321"
        #else
        return "https://khahcozfbnpykspvatrg.supabase.co"
        #endif
    }

    static var supabaseAnonKey: String {
        if let envKey = ProcessInfo.processInfo.environment["SUPABASE_ANON_KEY"] {
            return envKey
        }
        #if DEBUG
        return localAnonKey
        #else
        // Production anon key — set via environment variable
        return ""
        #endif
    }

    static var apiURL: String {
        // Backend API URL for server-side operations
        #if DEBUG
        // Local development API
        return ProcessInfo.processInfo.environment["SELKO_API_URL"] ?? "http://localhost:8000"
        #else
        // Production API
        return ProcessInfo.processInfo.environment["SELKO_API_URL"] ?? ""
        #endif
    }
}
