package net.melisma.selko.ui.theme

import androidx.compose.ui.graphics.Color

// Warmth light palette
val SelkoPrimary = Color(0xFFE86F52)
val SelkoOnPrimary = Color(0xFF2B2622)
val SelkoPrimaryContainer = Color(0xFFFCE2D9)
val SelkoOnPrimaryContainer = Color(0xFF2B2622)
val SelkoBackground = Color(0xFFFBF7F2)
val SelkoOnBackground = Color(0xFF2B2622)
val SelkoSurface = Color(0xFFFFFFFF)
val SelkoOnSurface = Color(0xFF2B2622)
val SelkoSurfaceVariant = Color(0xFFF5EEE6)
val SelkoOnSurfaceVariant = Color(0xFF746A61)
val SelkoOutline = Color(0xFFEDE4DA)
val SelkoOutlineVariant = Color(0xFFE7DBCF)
val SelkoDivider = Color(0xFFF2EAE1)
val SelkoFaint = Color(0xFF786E65)
val SelkoRust = Color(0xFFB4553A)
val SelkoLink = Color(0xFFC9603F)
val SelkoChanged = Color(0xFFC97A2E)

// Warmth dark palette
val SelkoPrimaryDark = Color(0xFFF0805C)
val SelkoOnPrimaryDark = Color(0xFF1A1613)
val SelkoPrimaryContainerDark = Color(0xFF4C2820)
val SelkoOnPrimaryContainerDark = Color(0xFFF2ECE4)
val SelkoBackgroundDark = Color(0xFF1A1613)
val SelkoOnBackgroundDark = Color(0xFFF2ECE4)
val SelkoSurfaceDark = Color(0xFF241F1B)
val SelkoOnSurfaceDark = Color(0xFFF2ECE4)
val SelkoSurfaceVariantDark = Color(0xFF2C2621)
val SelkoOnSurfaceVariantDark = Color(0xFFA99E92)
val SelkoOutlineDark = Color(0xFF322B25)
val SelkoOutlineVariantDark = Color(0xFF3A312A)
val SelkoDividerDark = Color(0xFF322B25)
val SelkoFaintDark = Color(0xFF8E8378)
val SelkoRustDark = Color(0xFFF0805C)
val SelkoLinkDark = Color(0xFFF0805C)
val SelkoChangedDark = Color(0xFFF0B45C)

// Semantic colors
val SelkoSuccess = Color(0xFF5CA07C)
val SelkoOnSuccess = Color(0xFF12100E)
val SelkoSuccessText = Color(0xFF3F7D5F)
val SelkoSuccessContainer = Color(0xFFDDEFE4)
val SelkoOnSuccessContainer = Color(0xFF214A35)
val SelkoSuccessDark = Color(0xFF5FBE90)
val SelkoSuccessContainerDark = Color(0xFF244A37)
val SelkoOnSuccessContainerDark = Color(0xFFD8F4E2)
val SelkoError = Color(0xFFAD3650)
val SelkoOnError = Color(0xFFFFFFFF)
val SelkoErrorDark = Color(0xFFEE7189)
val SelkoWarning = Color(0xFFF0A85C)
val SelkoOnWarning = Color(0xFF2B2622)
val SelkoWarningDark = Color(0xFFF0B45C)

// Status badge colors
val SelkoBadgeNewBackground = Color(0xFFF5EEE6)
val SelkoBadgeNewForeground = Color(0xFF6E655C)
val SelkoBadgeChangedBackground = Color(0xFFFDF1E7)
val SelkoBadgeChangedForeground = Color(0xFF9A5C1D)
val SelkoBadgeNewBackgroundDark = Color(0xFF2C2621)
val SelkoBadgeNewForegroundDark = Color(0xFFB8AC9F)
val SelkoBadgeChangedBackgroundDark = Color(0xFF3A2A20)
val SelkoBadgeChangedForegroundDark = Color(0xFFF0B45C)
